ARG BUILDTAG=build
FROM diproxy:${BUILDTAG}

COPY diproxy/test-requirements.txt diproxy/.pylintrc diproxy/.coveragerc diproxy/
RUN pip install --no-cache-dir -r diproxy/test-requirements.txt
COPY diproxy/diproxy/tests diproxy/diproxy/tests
