ARG BUILDTAG=build
FROM keeper:${BUILDTAG}


COPY keeper/test-requirements.txt ./
COPY keeper/.pylintrc keeper/.coveragerc ./

COPY opticloud_client/report_client opticloud_client/report_client

RUN pip install --no-cache-dir -r test-requirements.txt


COPY keeper/report_server/tests keeper/report_server/tests
