ARG BUILDTAG=build
ARG IMAGE=bulldozer_api
FROM ${IMAGE}:${BUILDTAG}

COPY opticloud_client/bulldozer_client opticloud_client/bulldozer_client
COPY bulldozer/test-requirements.txt bulldozer/.pylintrc ./bulldozer/
RUN pip install --no-cache-dir -r bulldozer/test-requirements.txt
