ARG BUILDTAG=build
FROM auth:${BUILDTAG}

COPY tools/check_alembic_down_revisions tools/check_alembic_down_revisions
COPY opticloud_client/auth_client /usr/src/app/opticloud_client/auth_client
COPY auth/test-requirements.txt auth/test-requirements.txt
COPY auth/.pylintrc auth/.coveragerc ./auth/
RUN pip install --no-cache-dir -r auth/test-requirements.txt

COPY auth/auth_server/tests auth/auth_server/tests
