ARG BUILDTAG=build
ARG IMAGE=metroculus_api
FROM ${IMAGE}:${BUILDTAG}

COPY opticloud_client/metroculus_client opticloud_client/metroculus_client
COPY metroculus/test-requirements.txt metroculus/.pylintrc metroculus/.coveragerc ./metroculus/
RUN pip install --no-cache-dir -r metroculus/test-requirements.txt
COPY metroculus/metroculus_api/tests metroculus/metroculus_api/tests
