ARG BUILDTAG=build
FROM trapper_worker:${BUILDTAG}


COPY trapper/test-requirements.txt trapper/.pylintrc trapper/.coveragerc ./trapper/
RUN pip install --no-cache-dir -r trapper/test-requirements.txt
