ARG BUILDTAG=build
FROM layout_cleaner:${BUILDTAG}


COPY docker_images/layout_cleaner/test-requirements.txt  docker_images/layout_cleaner/.pylintrc docker_images/layout_cleaner/
RUN pip install --no-cache-dir -r docker_images/layout_cleaner/test-requirements.txt
