ARG BUILDTAG=build
FROM katara_service:${BUILDTAG}
WORKDIR /usr/src/app/

COPY katara/katara_service/test-requirements.txt katara/test-requirements.txt
COPY katara/.pylintrc katara/.coveragerc ./katara/katara_service/

COPY tools/check_alembic_down_revisions tools/check_alembic_down_revisions
COPY opticloud_client/katara_client opticloud_client/katara_client

RUN pip install --no-cache-dir -r katara/test-requirements.txt
COPY katara/katara_service/tests katara/katara_service/tests
