ARG BUILDTAG=build
FROM pharos_worker:${BUILDTAG}


WORKDIR /usr/src/app/

COPY pharos_backend/pharos_worker/test-requirements.txt .

COPY pharos_backend/.pylintrc pharos_backend/.coveragerc ./
RUN pip install --no-cache-dir -r test-requirements.txt
