ARG BUILDTAG=build
ARG IMAGE=insider_api
FROM ${IMAGE}:${BUILDTAG}

COPY opticloud_client/insider_client opticloud_client/insider_client
COPY insider/test-requirements.txt insider/.pylintrc insider/.coveragerc ./insider/
RUN pip install --no-cache-dir -r insider/test-requirements.txt
COPY insider/insider_api/tests insider/insider_api/tests
