ARG BUILDTAG=build
ARG IMAGE=bulldozer_worker
FROM ${IMAGE}:${BUILDTAG}

COPY bulldozer/test-requirements.txt bulldozer/.pylintrc ./bulldozer/
RUN pip install --no-cache-dir -r bulldozer/test-requirements.txt
